slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan  # Consume the filtered /scan topic.
    mode: mapping

    map_update_interval: 1.0
    transform_publish_period: 0.02  # Publish TF at the controller update period.
    resolution: 0.05

    max_laser_range: 20.0  # Limit mapping to the configured LiDAR range.
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
