laser_filter:
  ros__parameters:
    tf_message_filter_target_frame: base_link  # Transform scans into base_link for downstream localization.
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.25
        max_x: 0.90
        min_y: -0.50
        max_y: 0.50
        min_z: -0.17
        max_z: 0.39